### ISSUE TITLE
Scss: Wrong color for variable when used in interpolation.

### ISSUE THREAD

**Issue by Lisa-Williams** [FlavourSys/Perv-ColorScheme#7]
Hi,
I just installed this color scheme.

There seems to be a problem with the coloring of variables when used for interpolation.
They are not colored white, but orange-red. (Screenshot.)

Could you tell me where to edit the color scheme?

Thx

Here is the code from the screenshot.

``` Scss
  $webfont-provider: '//fonts.googleapis.com/css?family=' !default;
  $webfont-family: 'Merriweather+Sans:400,300,300italic,400italic,700,700italic,800,800italic' !default;
  @import url(#{$webfont-provider}#{$webfont-family});

  %bg-dark {
    background-color: #000;
  }
  %bg-white{
    background-color: #FFF;
  }
  @mixin set-styles($arg) {
    @extend %bg-#{$arg};
  }
  .header {
    @include set-styles("dark");
  }
```

![perv-color-scheme-interpolation-wrong-variable-color.pngt](http://s22.postimg.org/93hahf4o1/perv_color_scheme_interpolation_wrong_variable_c.png)
